## Neural Sorting

This project explores the concept of sorting using neural networks.


In [2]:
"""Shared Configurations across cells"""

SEED = 777
LENGTH = 5
DATASET_SIZE = 10

## Dataset Generation

The dataset consist of a matrix with `DATASET_SIZE` rows and `LENGTH` columns.
Each row is random sample, used as input to the neural network. The target output is the sorted version of each row.

In [3]:
"""Dataset"""

import numpy as np

rng = np.random.default_rng(SEED)

X = rng.standard_normal((DATASET_SIZE, LENGTH))
print(X)

[[-0.84751551  0.06854253 -1.25092597 -1.58363669  0.63245758]
 [-0.46967539  1.18691531  0.37472157 -2.1419184  -0.42201634]
 [-1.10958753 -0.36247725  0.0893731   0.79418128 -1.52665076]
 [-1.28148383 -0.52021502 -1.23186944 -1.031033    0.37936595]
 [-1.75314511 -1.39137862  2.28808276 -1.88694486 -1.2238453 ]
 [-0.02568825 -0.85691081  0.31144987 -0.21642     0.81947569]
 [-0.2257357   1.07072276 -0.06013415 -0.24237197 -0.4442055 ]
 [ 0.06067046  0.54857195 -0.12988052  0.73795215  0.56263788]
 [ 0.21875695 -0.19517742 -0.99383496 -1.06815395  0.7726736 ]
 [ 1.19008817 -1.84103105  2.01526206 -0.34359036 -0.71923634]]


## Loss function

The loss function compute the total entropy of a vector of numbers.
Entropy in this context must be interpreted as a measure of disorder, less the entropy, more ordered the vector is. The loss function is defined as follows:

`loss(x) = sum(|x_i - x_(i-1)|)
starting from i=1
`

Basically the loss function is the reduction sum of the absolute value of differences between each consecutive pair of elements in the vector.

## Loss validation (numerically)

A simple validation of the loss function can be done by computing the loss of a sorted vector and an unsorted vector `N` times, for `N` big enough we should think that the loss is correct. 

In [13]:
"""Unit Test for loss function"""

import numpy as np
from loss import disorder

LENGTH_UPTO = 12
N = 1000000

for length in range(2, LENGTH_UPTO):
    X = rng.standard_normal((N, LENGTH))
    loss_test_dataset = np.stack([X, np.sort(X)])
    loss_test_dataset = loss_test_dataset.swapaxes(0, 1)

    for i, (x, y) in enumerate(loss_test_dataset):
        random_disorder = round(disorder(x), 5)
        sorted_disorder = round(disorder(y), 5)

        try:
            assert sorted_disorder <= random_disorder
        except:
            print(f'iter={i}, lenght={length}')
            print(f"random disorder={disorder(x)}")
            print(f"sorted disorder={disorder(y)}")
            print('-----------------------------------------')
            print(f"random={x}")
            print(f"sorted={y}")
            break

## 3 Scenarios

### Scenario 1: Learn how to sort a specific permutation of the same vector
### Scenario 2: Learn how to sort a specific set of numbers
### Scenario 3: Learn how to generalize to arbitrary set of numbers

## Scenario 1: Learn how to sort a specific permutation of the same vector

The whole scenario consist in train the network to learn a specific permutation matrix that if applied to a specific vector, it will sort it. 